### ISSUE TITLE
chunk unclaim bug

### ISSUE THREAD

**Issue by uisufian** [cjburkey01/ClaimChunk#22] opened 2017-09-17 12:50 UTC
`[18:48:13 INFO]: uisufian issued server command: /chunk unclaim
[18:48:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chunk' in plugin ClaimChunk v0.0.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IndexOutOfBoundsException: No group 2
        at java.util.regex.Matcher.start(Unknown Source) ~[?:1.8.0_131]
        at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_131]
        at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_131]
        at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_131]
        at com.cjburkey.claimchunk.cmd.MainHandler.unclaimChunk(MainHandler.java:81) ~[?:?]
        at com.cjburkey.claimchunk.cmds.CmdUnclaim.onCall(CmdUnclaim.java:31) ~[?:?]
        at com.cjburkey.claimchunk.cmd.CommandHandler.runCommands(CommandHandler.java:79) ~[?:?]
        at com.cjburkey.claimchunk.cmd.CommandHandler.onCommand(CommandHandler.java:48) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        ... 15 more
>
'

**Comment by DeathsGun** [comment] 2017-09-17 13:04
Can you give some steps to reproduce?

**Comment by uisufian** [comment] 2017-09-17 22:28
yaa.. sure what you want me to do

**Comment by uisufian** [comment] 2017-09-18 05:53
https://pastebin.com/CQTBEHY7

**Comment by cooldany** [comment] 2018-02-13 17:29
I have the same problem

**Comment by cooldany** [comment] 2018-02-13 17:31
on the version 1.12.2

**Comment by cjburkey01** [comment] 2018-02-13 23:03
Can you upload your config.yml? It looks like it might be your language section got messed up.

**Comment by cooldany** [comment] 2018-02-17 19:02
https://hastebin.com/oxomumupok.vbs

**Comment by cjburkey01** [comment] 2018-02-17 19:14
But your config.yml, what is `unclaimRefund` set to in your `messages` section? Does it look like: `unclaimRefund: 'You have been refunded %%AMT%%.'`?

**Comment by cjburkey01** [comment] 2018-05-28 03:46
I am going to close this issue, if you continue to have problems, don't hesitate to reopen the issue.

**Closed by cjburkey01** 2018-05-28 03:46 UTC
