### ISSUE TITLE
Claims lose owner data on server restart

### ISSUE THREAD

**Issue by codeHusky** [cjburkey01/ClaimChunk#217] opened 2021-10-02 09:09 UTC
**Versions**
Spigot Version: Airplane version git-Airplane-87 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 002f470 on HEAD)
ClaimChunk Version: 0.0.23-prev13

**Describe the bug**
After restarting the server with useDatabase: true and properly configured with no errors, player claims will fail to load properly until the relevant player logs in again. This prevents people the owner has trusted to access the claim being unable to access the claim.

**To Reproduce**
1. Create a claim in a server with useDatabase enabled
2. Restart server
3. Check if claim has owner data by right clicking a block

**Expected behavior**
Data about the claim is held and players are notified of the owner's name. Players who have been granted access to the claim remain having access to the claim.

**Additional context**
Full config:
```
# Config generated for ClaimChunk version 0.0.23-prev13
# For more information about all these options, please visit the wiki page:
# https://github.com/cjburkey01/ClaimChunk/wiki/Configuration-File

basic:
  disablePermissions: false
  checkForUpdates: true
log:
  debugSpam: false
  anonymousMetrics: true
  debug: false
titles:
  useTitlesInsteadOfChat: true
  useActionBar: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20
colors:
  infoColor: GREEN
  errorColor: RED
chunks:
  maxChunksClaimed: 25
  particlesWhenClaiming: true
  hideAlertsForVanishedPlayers: true
  automaticUnclaimSeconds: -1
  unclaimCheckIntervalTicks: 1200
  displayNameOfOwner: true
  defaultSendAlertsToOwner: true
  maxPerListPage: 5
  disabledWorlds: []
protection:
  blockedCmds: []
  disableOfflineProtect: false
worldguard:
  allowClaimsInRegionsByDefault: false
  allowClaimingInNonGuardedWorlds: true
  allowAdminOverride: true
economy:
  useEconomy: false
  claimPrice: 100.0
  unclaimReward: 10.0
  firstFreeChunks: 0
data:
  keepJsonBackups: true
  saveDataIntervalInMinutes: 10
  minBackupIntervalInMinutes: 120
  deleteOldBackupsAfterMinutes: 10080
database:
  useDatabase: true
  groupRequests: true
  convertOldData: true
  hostname: localhost
  port: 3306
  database: minecraft
  username: <removed>
  password: <removed>
  printDebug: false
  useSsl: false
  allowPublicKeyRetrieval: false
chunkOutline:
  name: SMOKE_LARGE
  durationSeconds: 5
  spawnsPerSecond: 2
  particlesPerSpawn: 2
  heightRadius: 3
floodclaim:
  enabled: true
  maximumIterations: 6
  maximumArea: 41
```

**Comment by codeHusky** [comment] 2021-10-02 09:57
Should note that it seems that access data is getting completely wiped on reboots

**Comment by cjburkey01** [comment] 2021-10-02 17:19
well that's not good lol, i do plan on removing mysql support in the near future because claimchunk makes no more efficient use of it and it ends up being slower >50% of the time probably, would you be able to switch back to the default data handler?

**Comment by codeHusky** [comment] 2021-10-02 22:30
@cjburkey01 is there a clean way to transition all the data? this is on a live server with 500+ players

**Comment by cjburkey01** [comment] 2021-10-03 01:22
Dang it i wish there was, i didn't realize the conversion code only goes one way by default, I need to make a new build that pulls down from SQL automatically. Once i get home tonight i can make a custom build that does it automatically for you

**Comment by cjburkey01** [comment] 2021-10-03 02:34
Ok, temporary solution is to download this version, run it once, and see if it created and filled your claimedChunks.json and joinedPlayers.json file?

[claimchunk-0.0.23-prev13-CONV_DB_TO_JSON-plugin.jar.zip](https://github.com/cjburkey01/ClaimChunk/files/7272563/claimchunk-0.0.23-prev13-CONV_DB_TO_JSON-plugin.jar.zip)

**Comment by codeHusky** [comment] 2021-10-03 05:25
didn't work, don't see those files anywhere in the folder

**Comment by cjburkey01** [comment] 2021-10-03 17:46
ah cool, yeah need to remove that. once you fixed the version string did the conversion work as intended?

**Comment by codeHusky** [comment] 2021-10-04 02:25
@cjburkey01 yes but i had to do /chunk admin reload cause it didnt occur on reboot automatically for whatever reason

**Comment by cjburkey01** [comment] 2021-10-04 03:27
that's another thing that needs to be disabled (or fixed), the reload command isn't very stable at the moment. as for why it needed a reload, I'm not entirely sure, but the instability is caused by reloading working exactly as unloading and loading the plugin again, did you fully stop your server before modifying everything? that's the only thing i can even think of as to why but idk

**Comment by codeHusky** [comment] 2021-10-04 04:59
@cjburkey01 yes it was fully stopped

**Comment by cjburkey01** [comment] 2021-10-04 13:37
definitely odd, hopefully before 0.0.23 i have most of these quirks worked out

**Comment by cjburkey01** [comment] 2021-12-19 03:28
Closing for more specific issue: https://github.com/cjburkey01/ClaimChunk/issues/230

**Closed by cjburkey01** 2021-12-19 03:28 UTC
