### ISSUE TITLE
Konsole gets Spammed with WARNs (Paper 1.17.1)

### ISSUE THREAD

**Issue by TheToady** [cjburkey01/ClaimChunk#225] opened 2021-11-24 15:22 UTC
**Versions**
Spigot Version: Paper 1.17.1
ClaimChunk Version: 0.0.22

**Describe the bug**
The whole plugin is working fine, except of the titles and the console gets spammed with these warnings:

[16:56:13 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutTitle
[16:56:13 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[16:56:13 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:56:13 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:56:13 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:56:13 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[16:56:13 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.PacketHandler.getNMSClass(PacketHandler.java:32)
[16:56:13 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.TitleHandler.showTitle(TitleHandler.java:78)
[16:56:13 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.TitleHandler.showTitle(TitleHandler.java:31)
[16:56:13 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.Utils.toPlayer(Utils.java:58)
[16:56:13 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.event.PlayerMovementHandler.onPlayerMove(PlayerMovementHandler.java:70)
[16:56:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor458.execute(Unknown Source)
[16:56:13 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:56:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:56:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:56:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[16:56:13 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1482)
[16:56:13 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:114)
[16:56:13 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPositionLook.a(PacketPlayInFlying.java:16)
[16:56:13 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[16:56:13 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:56:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:56:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[16:56:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[16:56:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[16:56:13 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:56:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**To Reproduce**
Idk install claimchunk on 1.17.1

**Comment by Geolykt** [comment] 2021-11-24 15:51
Duplicate of #208, #214

**Closed** 2021-11-24 17:03 UTC
