### ISSUE TITLE
Fire Still Spreading with blockFireSpread set to true

### ISSUE THREAD

**Issue by ThoolooExpress** [cjburkey01/ClaimChunk#133] opened 2020-04-01 19:20 UTC
**Versions**
Spigot Version: Paper Build 155
ClaimChunk Version: 0.0.20

**Describe the bug**
The blockFireSpread options is not disabling fire spread in claimed chunks as expected.

**To Reproduce**
1. Set gamerule doFireTick to true.
2. Claim a chunk.
3. Set a fire outside said chunk and watch it burn into your claimed chunk if it has a path.

**Expected behavior**
Fire should not be spreading in claimed chunks.

**Comment by cjburkey01** [comment] 2020-04-01 20:02
Now technically the intended behavior is that it’ll block fire spreading into claimed chunks not within the chunks but enough people have asked about this so I’ll switch it to this idea 👍

**Comment by ThoolooExpress** [comment] 2020-04-01 21:17
Glad to hear you're looking at this issue!  

> Now technically the intended behavior is that it’ll block fire spreading into claimed chunks not within the chunks

That is what I assumed it was too, but it does not seem to be effectively doing that.  I set a fire outside a claimed chunk and it burned right into it.  I did test it as OP, I assumed that didn't matter because there was nothing in the documentation, but I haven't read enough of your code to see if that makes a difference.

Actually, what you described would be preferable to disabling fire in claimed chunks totally, as I don't like the idea of protecting my players from themselves too much.

**Comment by cjburkey01** [comment] 2020-04-01 21:18
Hm well if that’s not working then there’s a bigger problem lol, I’ll look into it. Thanks for the report!

**Comment by cjburkey01** [comment] 2021-01-26 02:43
This will end up being fixed in 0.0.23 as the protection system has been rewritten, you can track progress on that update part's issue here: https://github.com/cjburkey01/ClaimChunk/issues/130 (I'm going to close this issue to clear out some old ones that are being fixed)

**Closed by cjburkey01** 2021-01-26 02:43 UTC
Labels: bug, enhancement
