### ISSUE TITLE
You don't have enough money

### ISSUE THREAD

**Issue by mrproof999** [cjburkey01/ClaimChunk#139] opened 2020-04-24 13:33 UTC
**Versions**
Spigot Version: 1.12
ClaimChunk Version: 0.0.20

**Describe the bug**
Hello. when a player join for first time, they have 200€ money set, but when they try to claim chunks for 50€ it says that they have not enough money.

**To Reproduce**
1 make a new player join the server with default money set to random amout (EX 1000€)
2 claim a chunk

**Expected behavior**
The plugin should take the money from the player.

**Additional context**
none

**Comment by cjburkey01** [comment] 2020-04-24 20:47
Hm, I can’t remember if someone else mentioned this as a bug but it sounds familiar so I’m not sure. Anyway, do you have any console errors?

**Comment by mrproof999** [comment] 2020-04-25 14:11
No console errors..

**Comment by cjburkey01** [comment] 2020-06-06 18:21
Ok, so the issue is with the way I checked if a player exists and it was fixed in this quick little dirty release version: [HERE](https://cdn.discordapp.com/attachments/600076352607223850/716352952914411540/ClaimChunk-a0736d8bd5dfa02e63c637ff7fdec15319c94751-0.0.20-FIX.jar)

**Closed by cjburkey01** 2020-06-06 18:21 UTC
Labels: bug
