### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MrmaximoExcssum** [cjburkey01/ClaimChunk#144] opened 2020-06-19 18:58 UTC
1.15.2
Latest cc
**You cant open E-chests in other peoples claimed chunks**

**Comment by cjburkey01** [comment] 2020-06-21 18:16
I'll mark this as a duplicate of https://github.com/cjburkey01/ClaimChunk/issues/96 because it's the fix for this

**Closed by cjburkey01** 2020-06-21 18:16 UTC
Labels: duplicate
