### ISSUE TITLE
Gui menu and change fumes i want help pls

### ISSUE THREAD

**Issue by kirveq** [cjburkey01/ClaimChunk#89] opened 2019-09-03 16:48 UTC
hello i want help please. i want the GUI menu , and claim showing I want to change fumes.
I mean claim chunk to make the menu gui. ie open the menu window. there is a menu where we can select our land and make transactions. And can't we use anything else instead of fumes when claim field is showing , how can we set this? .
I can put a lot of sample photos for the GUI menu. I really want this support to take place

![0](https://user-images.githubusercontent.com/54855499/64192345-2ba85300-ce83-11e9-875e-045629c1beaf.png)
![1](https://user-images.githubusercontent.com/54855499/64192346-2ba85300-ce83-11e9-9893-a3328e0d203c.png)
![2](https://user-images.githubusercontent.com/54855499/64192347-2ba85300-ce83-11e9-9801-bb2c03e450ac.png)
![3](https://user-images.githubusercontent.com/54855499/64192348-2c40e980-ce83-11e9-96d1-5584ed024ce9.png)
![4](https://user-images.githubusercontent.com/54855499/64192350-2c40e980-ce83-11e9-9fb8-00920d91edf4.png)
![5](https://user-images.githubusercontent.com/54855499/64192352-2c40e980-ce83-11e9-9b55-be575509b640.png)
![6](https://user-images.githubusercontent.com/54855499/64192353-2c40e980-ce83-11e9-88c1-7605cfd09a59.png)
![7](https://user-images.githubusercontent.com/54855499/64192355-2cd98000-ce83-11e9-96ed-1c74608edcac.png)
![8](https://user-images.githubusercontent.com/54855499/64192357-2cd98000-ce83-11e9-9434-98c661f8a59d.png)
![9](https://user-images.githubusercontent.com/54855499/64192360-2cd98000-ce83-11e9-8964-aacc51398f9a.png) (text to all players claim expired)

not exactly the same if you want. we can arrange it very close to the plugin. If you think your plugin will be corrupted in this way, you can also write another plugin and contact me. But my opinion is that you can easily overcome it. Please help me.

**Comment by cjburkey01** [comment] 2019-09-03 17:16
Duplicate of https://github.com/cjburkey01/ClaimChunk/issues/66 and https://github.com/cjburkey01/ClaimChunk/issues/88

I do like the graphics though, I'll reference those when working on the GUI system

**Closed by cjburkey01** 2019-09-03 17:16 UTC
